# Generated by Django 4.1b1 on 2025-12-21 14:25

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('learning_logs', '0003_topic_owner'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='entry',
            options={'ordering': ['-date_added'], 'verbose_name': '笔记', 'verbose_name_plural': '笔记'},
        ),
        migrations.AlterModelOptions(
            name='topic',
            options={'ordering': ['-date_added'], 'verbose_name': '主题', 'verbose_name_plural': '主题'},
        ),
        migrations.AlterField(
            model_name='entry',
            name='date_added',
            field=models.DateTimeField(auto_now_add=True, help_text='笔记创建的时间', verbose_name='创建时间'),
        ),
        migrations.AlterField(
            model_name='entry',
            name='text',
            field=models.TextField(help_text='记录你在这个主题上学到的知识', verbose_name='笔记内容'),
        ),
        migrations.AlterField(
            model_name='entry',
            name='topic',
            field=models.ForeignKey(help_text='此笔记所属的学习主题', on_delete=django.db.models.deletion.CASCADE, to='learning_logs.topic', verbose_name='所属主题'),
        ),
        migrations.AlterField(
            model_name='topic',
            name='date_added',
            field=models.DateTimeField(auto_now_add=True, help_text='主题创建的时间', verbose_name='创建时间'),
        ),
        migrations.AlterField(
            model_name='topic',
            name='owner',
            field=models.ForeignKey(help_text='拥有此主题的用户', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='所有者'),
        ),
        migrations.AlterField(
            model_name='topic',
            name='text',
            field=models.CharField(help_text='请输入学习主题的名称（最多200个字符）', max_length=200, verbose_name='主题名称'),
        ),
        migrations.AddIndex(
            model_name='entry',
            index=models.Index(fields=['topic', '-date_added'], name='entry_topic_date_idx'),
        ),
        migrations.AddIndex(
            model_name='topic',
            index=models.Index(fields=['owner', '-date_added'], name='topic_owner_date_idx'),
        ),
        migrations.AddIndex(
            model_name='topic',
            index=models.Index(fields=['text'], name='topic_text_idx'),
        ),
    ]
