# Generated by Django 4.1b1 on 2025-12-22 03:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learning_logs', '0004_alter_entry_options_alter_topic_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='entry',
            name='is_markdown',
            field=models.BooleanField(default=True, help_text='是否使用 Markdown 格式渲染', verbose_name='使用 Markdown'),
        ),
        migrations.AddField(
            model_name='entry',
            name='tags',
            field=models.CharField(blank=True, help_text='用逗号分隔的标签（例如：重要,总结,问题）', max_length=200, verbose_name='标签'),
        ),
        migrations.AddField(
            model_name='topic',
            name='color',
            field=models.CharField(choices=[('primary', '蓝色'), ('success', '绿色'), ('warning', '黄色'), ('danger', '红色'), ('info', '青色'), ('secondary', '灰色'), ('dark', '深色')], default='primary', help_text='选择主题的显示颜色', max_length=20, verbose_name='主题颜色'),
        ),
        migrations.AddField(
            model_name='topic',
            name='icon',
            field=models.CharField(default='📌', help_text='为主题选择一个图标（emoji）', max_length=50, verbose_name='主题图标'),
        ),
        migrations.AlterField(
            model_name='entry',
            name='text',
            field=models.TextField(help_text='记录你在这个主题上学到的知识（支持 Markdown 格式）', verbose_name='笔记内容'),
        ),
    ]
