# Generated by Django 4.1b1 on 2025-12-22 14:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learning_logs', '0005_entry_is_markdown_entry_tags_topic_color_topic_icon_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='topic',
            name='cover_image_url',
            field=models.URLField(blank=True, help_text='可选，粘贴一张图片的网络地址作为封面（例如来自图床或 Unsplash）', max_length=300, verbose_name='主题封面图片链接'),
        ),
    ]
