# Generated by Django 4.1b1 on 2025-12-23 04:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learning_logs', '0006_topic_cover_image_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='entry',
            name='is_public',
            field=models.BooleanField(default=False, help_text='选择"公开"后，此笔记将发布到博客论坛，所有人可以查看和评论；选择"私密"则仅自己可见', verbose_name='公开/私密'),
        ),
    ]
